version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: cinema-db
    environment:
      - POSTGRES_USER=cinema
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cinema
    restart: unless-stopped
    ports:
      - '5432:5432'

  cinema:
    container_name: cinema-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://cinema-db:5432/cinema
      - SPRING_DATASOURCE_USERNAME=cinema
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
